@echo off
REM ========================================================================
REM CVGen - Quantum Computing for Every Device
REM Windows Setup Script
REM
REM This script handles complete setup of CVGen with Docker on Windows
REM ========================================================================

setlocal enabledelayedexpansion

REM Color codes for output (limited on Windows)
set "GREEN=[OK]"
set "RED=[ERROR]"
set "YELLOW=[WARNING]"
set "BLUE=[INFO]"

REM Configuration
set "SCRIPT_DIR=%~dp0"
set "ENV_FILE=%SCRIPT_DIR%.env"
set "COMPOSE_FILE=%SCRIPT_DIR%docker-compose.full.yml"

REM ========================================================================
REM Utility Functions
REM ========================================================================

:print_header
echo.
echo ====================================================
echo %~1
echo ====================================================
echo.
exit /b 0

:print_status
echo %~1 %~2
exit /b 0

:print_section
echo.
echo -- %~1
echo.
exit /b 0

:ask_yes_no
setlocal
set "prompt=%~1"
:ask_loop
set /p "response=%prompt% (y/n): "
if /i "%response%"=="y" (
    endlocal & exit /b 0
)
if /i "%response%"=="n" (
    endlocal & exit /b 1
)
goto ask_loop

REM ========================================================================
REM Detection Functions
REM ========================================================================

:detect_ram
REM Get RAM in GB
for /f "tokens=2" %%A in ('wmic OS get TotalVisibleMemorySize /value ^| find "="') do set /a "total_ram_kb=%%A"
set /a "total_ram_gb=!total_ram_kb! / 1048576"
echo !total_ram_gb!
exit /b 0

:check_docker_installed
where docker >nul 2>nul
if %errorlevel% equ 0 (
    exit /b 0
) else (
    exit /b 1
)

:check_docker_compose_installed
where docker-compose >nul 2>nul
if %errorlevel% equ 0 (
    exit /b 0
) else (
    docker compose version >nul 2>nul
    exit /b %errorlevel%
)

:check_docker_running
docker ps >nul 2>nul
exit /b %errorlevel%

REM ========================================================================
REM Configuration Functions
REM ========================================================================

:recommend_model_for_ram
setlocal
set "ram=%~1"
if %ram% lss 4 (
    echo phi3:mini
) else if %ram% lss 8 (
    echo qwen2.5:7b
) else if %ram% lss 16 (
    echo qwen2.5:14b
) else if %ram% lss 32 (
    echo qwen2.5:14b
) else (
    echo qwen2.5:32b
)
endlocal
exit /b 0

:create_env_file
setlocal
set "model=%~1"
set "port=%~2"

(
    echo # ================================================================
    echo # CVGen Configuration - Generated by setup.bat
    echo # ================================================================
    echo.
    echo # CVGen API Configuration
    echo CVGEN_PORT=%port%
    echo CVGEN_HOST=0.0.0.0
    echo CVGEN_LOG_LEVEL=INFO
    echo CVGEN_API_URL=http://cvgen:8000
    echo.
    echo # Ollama LLM Backend
    echo OLLAMA_MODEL=%model%
    echo OLLAMA_HOST=http://ollama:11434
    echo.
    echo # Qdrant Vector Database
    echo QDRANT_URL=http://qdrant:6333
    echo QDRANT_COLLECTION=cvgen_qpanda3
    echo.
    echo # Origin Pilot (Quantum Backend^)
    echo ORIGIN_PILOT_HOST=localhost
    echo ORIGIN_PILOT_JOB_PORT=5555
    echo ORIGIN_PILOT_TELEMETRY_PORT=5556
    echo.
    echo # IBM Quantum (optional^)
    echo # IBM_QUANTUM_TOKEN=
    echo # IBM_QUANTUM_BACKEND=ibm_brisbane
    echo.
    echo # AWS Braket (optional^)
    echo # AWS_DEFAULT_REGION=
    echo # AWS_ACCESS_KEY_ID=
    echo # AWS_SECRET_ACCESS_KEY=
    echo # CVGEN_BRAKET_S3_BUCKET=
    echo.
    echo # Azure Quantum (optional^)
    echo # AZURE_QUANTUM_RESOURCE_ID=
    echo # AZURE_QUANTUM_LOCATION=eastus
) > "%ENV_FILE%"

endlocal
exit /b 0

:start_services
echo.
echo Starting CVGen services...
echo This may take a few minutes on first run...
echo.

cd /d "%SCRIPT_DIR%"
docker-compose -f "%COMPOSE_FILE%" up -d
if %errorlevel% equ 0 (
    echo All containers started
    exit /b 0
) else (
    echo Failed to start containers
    exit /b 1
)

REM ========================================================================
REM Main Setup Flow
REM ========================================================================

:main
cls
call :print_header "CVGen Setup Script - Windows Edition"
echo Quantum Computing for Every Device
echo Docker All-in-One Stack
echo Version: Phase 4
echo.

REM System detection
call :print_section "System Detection"

call :detect_ram
set "ram_gb=%errorlevel%"

echo Detected RAM: !ram_gb!GB

REM Call recommend function - Note: batch has limitations with functions returning values
REM For simplicity, we'll just ask the user
call :print_section "Docker Verification"

call :check_docker_installed
if %errorlevel% neq 0 (
    echo Docker is not installed
    echo Please install Docker Desktop from: https://www.docker.com/products/docker-desktop
    start "" "https://www.docker.com/products/docker-desktop"
    pause
    exit /b 1
) else (
    echo Docker is installed
    docker --version
)

call :check_docker_compose_installed
if %errorlevel% neq 0 (
    echo Docker Compose is not installed
    exit /b 1
) else (
    echo Docker Compose is installed
)

call :check_docker_running
if %errorlevel% neq 0 (
    echo Docker daemon is not running
    echo Please start Docker Desktop and try again
    exit /b 1
) else (
    echo Docker daemon is running
)

REM Configuration
call :print_section "CVGen Configuration"
echo.
echo Available LLM Models (recommended for !ram_gb!GB RAM^):
echo   1. phi3:mini        - 2.2GB - Very fast
echo   2. qwen2.5:7b       - 4.0GB - Recommended
echo   3. mistral:latest   - 4.1GB - Fast coding
echo   4. qwen2.5:14b      - 8.9GB - Better quality
echo   5. qwen2.5:32b      - 20.3GB - Best quality
echo.

set /p model_choice="Select model (default 2 for qwen2.5:7b): "
if "%model_choice%"=="" set "model_choice=2"

if "%model_choice%"=="1" (
    set "model=phi3:mini"
) else if "%model_choice%"=="2" (
    set "model=qwen2.5:7b"
) else if "%model_choice%"=="3" (
    set "model=mistral:latest"
) else if "%model_choice%"=="4" (
    set "model=qwen2.5:14b"
) else if "%model_choice%"=="5" (
    set "model=qwen2.5:32b"
) else (
    set "model=qwen2.5:7b"
)

set /p port="Enter CVGen API port (default 8000): "
if "%port%"=="" set "port=8000"

REM Create env file
call :create_env_file "%model%" "%port%"
echo Configuration saved to .env

REM Start services
call :print_section "Starting CVGen Services"
call :start_services
if %errorlevel% neq 0 (
    echo.
    echo Failed to start services. Please check:
    echo   - Docker Desktop is running
    echo   - You have sufficient disk space
    echo   - Run: docker-compose -f docker-compose.full.yml logs
    pause
    exit /b 1
)

REM Display next steps
call :print_header "Setup Complete!"
echo.
echo CVGen is now starting. Services will be ready in a few moments.
echo.
echo Available services:
echo   - CVGen Web UI:       http://localhost:%port%
echo   - API Swagger Docs:   http://localhost:%port%/docs
echo   - Ollama:             http://localhost:11434
echo   - Qdrant:             http://localhost:6333
echo.
echo Useful commands:
echo   - View logs:         docker logs -f cvgen-api
echo   - Stop services:     docker-compose -f docker-compose.full.yml down
echo   - Restart services:  docker-compose -f docker-compose.full.yml restart
echo   - Health check:      bash scripts/health_check.sh
echo.
echo Configuration file:     %ENV_FILE%
echo.

set /p openBrowser="Open CVGen in your browser? (y/n): "
if /i "%openBrowser%"=="y" (
    start http://localhost:%port%
)

echo.
echo Setup script complete. You can close this window.
pause
